import { Project } from "./Project";

export const PROJECTS: Project[] = [
    {
        id: 0,
        title: 'Calorie Tracker',
        link: 'calorie-tracker',
        url: 'http://localhost:3000/',
        GitHub: 'https://github.com/WalkingZ3d/CalorieTracker2',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/fnc.png',
        framework: '../../../assets/images/frameworkIcons/node-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
    {
        id: 1,
        title: 'Jigsaw Helper',
        url: 'pending',
        GitHub: 'https://github.com/WalkingZ3d/JigsawHelper',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/fnc.png',
        framework: '../../../assets/images/frameworkIcons/java-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
    {
        id: 2,
        title: 'GitHub Tracker',
        url: 'https://dan-react-github-search.netlify.app/',
        GitHub: 'https://github.com/WalkingZ3d/github-tracker',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/fnc.png',
        framework: '../../../assets/images/frameworkIcons/react-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
    {
        id: 3,
        title: 'Calorie Tracker',
        link: 'calorie-tracker',
        url: 'http://localhost:3000/',
        GitHub: 'https://github.com/WalkingZ3d/CalorieTracker2',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/fnc.png',
        framework: '../../../assets/images/frameworkIcons/node-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
]