export interface Project {
    id?: number;
    title?: string;
    link?: string;
    url?: string;
    GitHub?: string;
    summary?: string;
    description?: String;
    picture?: string;
    stamp?: string;
    framework?: string;
    screenshot?: Array<Array<string>>;
    code?: Array<Array<string>>;
    // screenshot1?: string;
    // screenshot1Description?: string;
    // screenshot2?: string;
    // screenshot2Description?: string;
    // screenshot3?: string;
    // screenshot3Description?: string;
    // screenshot4?: string;
    // screenshot4Description?: string;
    // screenshot5?: string;
    // screenshot5Description?: string;
    // screenshot6?: string;
    // screenshot6Description?: string;
    // screenshot7?: string;
    // screenshot7Description?: string;
    // screenshot8?: string;
    // screenshot8Description?: string;
    // screenshot9?: string;
    // screenshot9Description?: string;
    // screenshot10?: string;
    // screenshot10Description?: string;
    // screenshot11?: string;
    // screenshot11Description?: string;
    // code1?: string;
    // code1Description?: string;
    // code2?: string;
    // code2Description?: string;
    // code3?: string;
    // code3Description?: string;
    // code4?: string;
    // code4Description?: string;
    // code5?: string;
    // code5Description?: string;
    // code6?: string;
    // code6Description?: string;
    // code7?: string;
    // code7Description?: string;
    // code8?: string;
    // code8Description?: string;
    // code9?: string;
    // code9Description?: string;
    // code10?: string;
    // code10Description?: string;
    // code11?: string;
    // code11Description?: string;
    // code12?: string;
    // code12Description?: string;
    // code13?: string;
    // code13Description?: string;
    // code14?: string;
    // code14Description?: string;
    // code15?: string;
    // code15Description?: string;
    // code16?: string;
    // code16Description?: string;
    // code17?: string;
    // code17Description?: string;
    // code18?: string;
    // code18Description?: string;
    // code19?: string;
    // code19Description?: string;
    // code20?: string;
    // code20Description?: string;
    // code21?: string;
    // code21Description?: string;
    // code22?: string;
    // code22Description?: string;
    // code23?: string;
    // code23Description?: string;
    // code24?: string;
    // code24Description?: string;
    // code25?: string;
    // code25Description?: string;
}