import { Project } from "./Project";

export const PROJECTS: Project[] = [
    {
        id: 0,
        title: 'Calorie Tracker',
        link: 'calorie-tracker',
        url: 'http://localhost:3000/',
        GitHub: 'https://github.com/WalkingZ3d/CalorieTracker2',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/personal-pink-clear.png',
        framework: '../../../assets/images/frameworkIcons/node-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
    {
        id: 1,
        title: 'Jigsaw Helper',
        GitHub: 'https://github.com/WalkingZ3d/JigsawHelper',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/jigsawHelper/gui.png',
        stamp: '../../../assets/images/stamps/personal-pink-clear.png',
        framework: '../../../assets/images/frameworkIcons/java-logo.png',
        screenshot1: '../../../assets/images/jigsawHelper/gui.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/jigsawHelper/hierloom-no-edge.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
    {
        id: 2,
        title: 'GitHub Searcher',
        url: 'https://dan-react-github-search.netlify.app/',
        GitHub: 'https://github.com/WalkingZ3d/github-tracker',
        summary: 'A React front-end exclusive application to search for a given users repositories. This application makes uese of React routing, state, reducers amd useEffect() Hooks to achieve its result.',
        description: 'A React front-end exclusive application to search for a given users repositories. This application makes uese of React routing, state, reducers amd useEffect() Hooks to achieve its result.',
        picture: '../../../assets/images/repoSearcher/main-screenshot.png',
        stamp: '../../../assets/images/stamps/personal-pink-clear.png',
        framework: '../../../assets/images/frameworkIcons/react-logo.png',
        screenshot1: '../../../assets/images/repoSearcher/main-screenshot.png',
        screenshot1Description: 'The homepage for the GitHub repository searcher. To use, simply enter a valid GitHub username and press the "Search" button. This will fire a GET request using axios to the GitHub API to retrieve the publicly listed repositories for that user.',
        screenshot2: '../../../assets/images/repoSearcher/screenshot-2.png',
        screenshot2Description: 'Once the GitHub API has been called, the page is populated with all of the titles of thats user\'s repositories. The user may choose how many results they want per page and use the "Next" and "Prev" buttons to navigate between pages of repositories. This page also includes a reset search button to allow a fresh search to be undertaken. When a user clicks on one of the titles, they are redirected to a new page with the searched username and title of the clicked repository in the URL parameters',
        screenshot3: '../../../assets/images/repoSearcher/screenshot-3.png',
        screenshot3Description: 'The page for information on each repository uses the URL parameters of username and repository title to make an axios GET request for data about said repository. This information is then slotted into a custom card component and displayed to the user.',
        screenshot4: '../../../assets/images/repoSearcher/screenshot-4.png',
        screenshot4Description: 'This page takes advantage of React Routing to provide the user with a custom 404 page if they navigate to a non-existant route.',
        code1: '../../../assets/images/repoSearcher/code-1.png',
        code1Description: 'This useEffect() React Hook is located in the source code for the "Search" page and fires whenever a new username is searched. The asynchronous function, seen between lines 20 and 29, makes a call to the GitHub API to update both the reposCount (number of repositories for that username) and ownerName (username) React States - called recursively on line 31. This method of nested async function is necessary as the useEffect itself cannot be asynchronous. ',
        code2: '../../../assets/images/repoSearcher/code-2.png',
        code2Description: 'This useEffect() is also located in the source code for the "Search" page and fires whenever the number of pages are changed, username is changed or a new page is navigated to. The async function, seen between lines 44 and 62, sets the number of pages required (lines 46 and 47) and calls the API to get as many repositories as each page will show. This function is also called recursively within the useEffect.',
        code3: '../../../assets/images/repoSearcher/code-3.png',
        code3Description: 'The function renderRepos(), lines 86-88, maps the gathered repository data to <li> elements for display on the page. Each one will navigate to the username/repositoryName upon click as the map allows for each link to use the title as a URL Parameter. RenderRepos() is called in the HTML return of this page. The 2 functions underneath (lines 90 - 105) handle the pagination controls of the Search page. Since the number of pages changes based on the user selection from a dropdown, these 2 functions use States to determine whether page navigation is possible or not. ',
        code4: '../../../assets/images/repoSearcher/code-4.png',
        code4Description: 'When the user clicks on a repository to see more information on the Search page, the username and repository name are added as URL parameters. On the Results page, the useParams() Hook (seen on line 9) is used to grab those peices of data for later use. The useEffect(), shown between lines 14 and 25, is fired whenever the name changes - which is upon navigation to the page. The async function within then makes a call to the GitHub API to gather data about that paticular repository and add it to the empty object of RepoData seen on line 10. A card is then generated for the data between lines 29 and 31.',
        code5: '../../../assets/images/repoSearcher/code-5.png',
        code5Description: 'The App uses React Routing to allow the user to believe they are moving between pages. Line 9 adds the basic layout of Header and Footer to all pages. Lines 10 - 15 are the nested routes required to allow the URL parameters to move to username/repositoryTitle and show the information to the user. Line 16 navigates the user to an about page where they can learn how to use the app. The final route on line 17 acts as a catch all to display a 404 page if the user tries to move to a URL that does not exist within the application.',
    },
    {
        id: 3,
        title: 'The Motive',
        link: 'calorie-tracker',
        url: 'http://localhost:3000/',
        GitHub: 'https://github.com/WalkingZ3d/CalorieTracker2',
        summary: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        picture: '../../../assets/images/calorieTracker/calorieTracker.png',
        stamp: '../../../assets/images/stamps/collaborative-pink-clear.png',
        framework: '../../../assets/images/frameworkIcons/node-logo.png',
        screenshot1: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot2: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        screenshot3: '../../../assets/images/calorieTracker/calorieTracker.png',
        screenshot3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code1: '../../../assets/images/fnc.png',
        code1Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code2: '../../../assets/images/fnc.png',
        code2Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
        code3: '../../../assets/images/fnc.png',
        code3Description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae enim cum similique voluptas nulla? Repellat autem, incidunt magni culpa non illo, soluta quidem fugit voluptas doloremque necessitatibus at optio. Ab.',
    },
]